### PR TITLE
replace memcached gem with dalli

### PR DESCRIPTION
**Pull request by bleything**
This is an alternative to sensu-plugins/sensu-plugins-memcached#7 which replaces memcached gem with the pure-ruby [dalli](https://github.com/petergoldstein/dalli). See that PR for the details and background.

### CODE REVIEW

**Comment by majormoses** [comment]
Hmm I do like the fact that with the other method we remove any new deps and in that case it was fairly easy to port. On the other hand I think it will be easier to have people contribute with `dali` over talking to sockets directly. Ping @sensu-plugins/ruby_plugins_commit_bit thoughts?

**Comment by eheydrick** [comment]
The `memcached` gem hasn't been updated in 4 years so moving to `dalli` seems reasonable as a replacement.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-memcached/versions/0.1.3

**Comment by bleything** [comment]
Thanks!

**Pull request merged**
